from typing_extensions import TypedDict
from datetime import date
from typing import Optional


class GraphState(TypedDict):
    """
    State schema representing variables passed through nodes in the AI graph.
    """
    symbol: str
    date: date
    remaining_days: int
    
    # Recommendation dictionary generated by the Decision Engine
    recommendation: dict
    
    # Synthesized component summaries
    market_text: Optional[str]
    news_text: Optional[str]
    macro_text: Optional[str]
    summary_text: Optional[str]
    
    # AI explanation outcomes
    ai_explanation: Optional[str]
    telegram_text: Optional[str]
